# Generated by Django 4.2.6 on 2023-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('comfort_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comfort_plus_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exclusive_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
